In [1]:
import fastf1
print(fastf1.__version__)

3.8.3

In [3]:
import os

# Crear la carpeta de caché si no existe (exist_ok=True evita error si ya existe)
os.makedirs('../cache', exist_ok=True)
print('Caché en:', os.path.abspath('../cache'))

fastf1.Cache.enable_cache('../cache')

session = fastf1.get_session(2024, 'Monza', 'R')
session.load()

Caché en: /Users/alvaroruiz/Desktop/proyecto f1/cache

core           INFO 	Loading data for Italian Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['16', '81', '4', '55', '44', '1', '63', '11', '23', '20', '14', '43', '3', '31', '10', '77', '27', '24', '18', '22']

In [4]:
os.getcwd()

'/Users/alvaroruiz/Desktop/proyecto f1/f1-strategy-analytics'

In [5]:
os.makedirs('cache', exist_ok=True)
...
fastf1.Cache.enable_cache('cache')

In [6]:
session.results[['Abbreviation', 'TeamName', 'GridPosition', 'Position', 'Points', 'Status']]

   Abbreviation         TeamName  GridPosition  Position  Points    Status
16          LEC          Ferrari           4.0       1.0    25.0  Finished
81          PIA          McLaren           2.0       2.0    18.0  Finished
4           NOR          McLaren           1.0       3.0    16.0  Finished
55          SAI          Ferrari           5.0       4.0    12.0  Finished
44          HAM         Mercedes           6.0       5.0    10.0  Finished
1           VER  Red Bull Racing           7.0       6.0     8.0  Finished
63          RUS         Mercedes           3.0       7.0     6.0  Finished
11          PER  Red Bull Racing           8.0       8.0     4.0  Finished
23          ALB         Williams           9.0       9.0     2.0  Finished
20          MAG     Haas F1 Team          13.0      10.0     1.0  Finished
14          ALO     Aston Martin          11.0      11.0     0.0  Finished
43          COL         Williams          18.0      12.0     0.0  Finished
3           RIC               RB          12.0      13.0     0.0  Finished
31          OCO           Alpine          15.0      14.0     0.0    Lapped
10          GAS           Alpine          14.0      15.0     0.0    Lapped
77          BOT      Kick Sauber          19.0      16.0     0.0    Lapped
27          HUL     Haas F1 Team          10.0      17.0     0.0    Lapped
24          ZHO      Kick Sauber          20.0      18.0     0.0    Lapped
18          STR     Aston Martin          17.0      19.0     0.0    Lapped
22          TSU               RB          16.0      20.0     0.0   Retired

In [7]:
# Copiamos las columnas que nos interesan
res = session.results[['Abbreviation', 'TeamName', 'GridPosition', 'Position']].copy()

# Posiciones ganadas = salida - llegada (positivo = remontó, negativo = perdió)
res['Ganadas'] = res['GridPosition'] - res['Position']

# Ordenamos de mayor remontada a mayor caída
res.sort_values('Ganadas', ascending=False)

   Abbreviation         TeamName  GridPosition  Position  Ganadas
43          COL         Williams          18.0      12.0      6.0
16          LEC          Ferrari           4.0       1.0      3.0
77          BOT      Kick Sauber          19.0      16.0      3.0
20          MAG     Haas F1 Team          13.0      10.0      3.0
24          ZHO      Kick Sauber          20.0      18.0      2.0
55          SAI          Ferrari           5.0       4.0      1.0
44          HAM         Mercedes           6.0       5.0      1.0
1           VER  Red Bull Racing           7.0       6.0      1.0
31          OCO           Alpine          15.0      14.0      1.0
81          PIA          McLaren           2.0       2.0      0.0
14          ALO     Aston Martin          11.0      11.0      0.0
23          ALB         Williams           9.0       9.0      0.0
11          PER  Red Bull Racing           8.0       8.0      0.0
3           RIC               RB          12.0      13.0     -1.0
10          GAS           Alpine          14.0      15.0     -1.0
4           NOR          McLaren           1.0       3.0     -2.0
18          STR     Aston Martin          17.0      19.0     -2.0
63          RUS         Mercedes           3.0       7.0     -4.0
22          TSU               RB          16.0      20.0     -4.0
27          HUL     Haas F1 Team          10.0      17.0     -7.0

In [8]:
laps = session.laps
laps.shape

(1008, 31)

In [9]:
laps.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:57:18.931000,LEC,16,0 days 00:01:28.179000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:29.989000,...,True,Ferrari,0 days 00:55:50.494000,2024-09-01 13:03:34.413,1,2.0,False,,False,False
1,0 days 00:58:44.327000,LEC,16,0 days 00:01:25.396000,2.0,1.0,NaT,NaT,0 days 00:00:27.707000,0 days 00:00:29.265000,...,True,Ferrari,0 days 00:57:18.931000,2024-09-01 13:05:02.850,1,2.0,False,,False,True
2,0 days 01:00:09.506000,LEC,16,0 days 00:01:25.179000,3.0,1.0,NaT,NaT,0 days 00:00:27.679000,0 days 00:00:29.001000,...,True,Ferrari,0 days 00:58:44.327000,2024-09-01 13:06:28.246,1,2.0,False,,False,True
3,0 days 01:01:34.316000,LEC,16,0 days 00:01:24.810000,4.0,1.0,NaT,NaT,0 days 00:00:27.653000,0 days 00:00:28.883000,...,True,Ferrari,0 days 01:00:09.506000,2024-09-01 13:07:53.425,1,2.0,False,,False,True
4,0 days 01:02:58.919000,LEC,16,0 days 00:01:24.603000,5.0,1.0,NaT,NaT,0 days 00:00:27.630000,0 days 00:00:28.790000,...,True,Ferrari,0 days 01:01:34.316000,2024-09-01 13:09:18.235,1,2.0,False,,False,True

In [10]:
laps.columns.tolist()

['Time',
 'Driver',
 'DriverNumber',
 'LapTime',
 'LapNumber',
 'Stint',
 'PitOutTime',
 'PitInTime',
 'Sector1Time',
 'Sector2Time',
 'Sector3Time',
 'Sector1SessionTime',
 'Sector2SessionTime',
 'Sector3SessionTime',
 'SpeedI1',
 'SpeedI2',
 'SpeedFL',
 'SpeedST',
 'IsPersonalBest',
 'Compound',
 'TyreLife',
 'FreshTyre',
 'Team',
 'LapStartTime',
 'LapStartDate',
 'TrackStatus',
 'Position',
 'Deleted',
 'DeletedReason',
 'FastF1Generated',
 'IsAccurate']

## Guía de columnas: `session.laps`

| Columna | Qué significa |
|---|---|
| `Driver`, `Team` | Piloto (abreviatura) y equipo |
| `LapNumber` | Número de vuelta |
| `LapTime` | Tiempo de la vuelta (timedelta, pasar a segundos) |
| `Sector1Time`–`Sector3Time` | Tiempo de cada uno de los 3 sectores |
| `Stint` | Tramo de carrera entre paradas (1 = primer juego de neumáticos) |
| `Compound` | Compuesto del neumático: SOFT, MEDIUM, HARD, INTERMEDIATE, WET |
| `TyreLife` | Vueltas que lleva ese neumático |
| `FreshTyre` | Si el neumático era nuevo al montarlo |
| `PitInTime`, `PitOutTime` | Momento de entrada y salida de boxes (vacío si no paró) |
| `SpeedI1`, `SpeedI2`, `SpeedFL`, `SpeedST` | Velocidad en 2 puntos intermedios, meta y trampa de velocidad (km/h) |
| `TrackStatus` | Estado de pista: 1 = verde, 2 = amarilla, 4 = safety car, 5 = roja, 6/7 = VSC |
| `Position` | Posición al final de la vuelta |
| `Deleted` | Vuelta anulada (por ejemplo, por límites de pista) |
| `IsAccurate` | Si FastF1 considera fiable el tiempo |

### Observaciones
- La vuelta 1 no es representativa: salida parada, sin `Sector1Time` e `IsAccurate = False`.
- Los tiempos bajan durante el stint por el efecto del combustible.